- README.md
- __tests__/Credentials-test.js
- __tests__/__snapshots__/Credentials-test.js.snap
- dist/uport.js
- src/Credentials.js
Private chain address can now be specified in a selective disclosure request
> Request private chain address

- dist/uport.js
- package.json
- tutorial/createcredential.js
- tutorial/requestcredential.js
- tutorial/tutorial.md
Updated `uport-js` tutorial so that it works on Rinkeby.
> feature(tutorial): Update tutorial for rinkeby

- DOCS.md
- package.json
- src/Credentials.js
- src/JWT.js
- src/SimpleSigner.js
> docs: add inline documentation (jsdoc)

- package.json
- tutorial/createcredential.js
- tutorial/requestcredential.js
- tutorial/tutorial.md
Updated tutorial with challenge/response. Remove deprecated Babel dependency.
> Update tutorial for challenge/resp. Remove babel.

- RELEASE-NOTES.md
- dist/uport.js
- package.json
- src/Credentials.js
- tutorial/createcredential.js
- tutorial/requestcredential.js
- tutorial/tutorial.md
- yarn.lock
This release fixes #24 and adds `yarn build` to the prepublish hook so that the npm package isn't missing the `lib` which is the main entrypoint of the library
> Release 0.5.2

- tutorial/tutorial.md
> fixes for docs site

- __tests__/Credentials-test.js
- dist/uport.js
- package.json
- src/Credentials.js
- yarn.lock
It also requires the user to specify a public encryption key. The reason it's not looked up from the registry is that we also require the user to specify a push token. When requesting the push token the user will also always get the encryption key.
[ch2349]
> Push method now always sends encrypted push notifications.

- __tests__/Credentials-test.js
- __tests__/JWT-test.js
- __tests__/__snapshots__/JWT-test.js.snap
- src/JWT.js
Also has better error messages for debugging
> Allow JWT's to have been issued within a minute in the future to allow for natural clock skew

- tutorial/createcredential.js
- tutorial/requestcredential.js
- tutorial/tutorial.md
Small update with support for complex claims, also clarified language in the tutorial text.
> Updates with complex claims.

- README.md
> Fix notice about "coming soon", because it's here!

- .gitignore
- LICENSE.txt
- docs/guides/server-side-credentials-example.md
- docs/reference/index.md
- js2doc.conf
- package-lock.json
- package.json
- src/__tests__/__snapshots__/Credentials-test.js.snap
- template.hbs
- webpack.config.js
- yarn.lock
> Feature/update did branch for docs for #71

- src/Credentials.js
This PR adds `riss` to the createVerificationSignatureRequest
Specs are here: 
https://github.com/uport-project/specs/blob/develop/messages/verificationreq.md
> Adding riss in createVerificationSignatureRequest

- docs/guides/tutorial.md
- examples/createcredential.js
- examples/requestcredential.js
- package-lock.json
- package.json
- Makes example quick an easy to use, by running with ngrok by default
- Add push example, and allows to easily get DID for credential creation, without telling dev to go find it somewhere, works out of box.
- Makes use of transports, instead of manually constructing 
- cleans up code 
- clean up message logging and adds better reference
- clarifies a few parts of tutorial doc
- add quick start section to doc and explicit get started commands
> feat: improve tutorial flow

- whats-new.md
Doc describing changes in major release
> doc: add new markdown file describing changes in 1.0 release

- docs/guides/tutorial.md
- examples/createcredential.js
Remove some confusing aspects, and add more copy to describe uport-transports, and the essence of the disclosure request flow
> doc: improve wording of the tutorial

- src/Credentials.js
update option names and descriptions for Credentials.createTypedDataSignatureRequest
> fix: update docstrings for typed data sig

- docs/reference/index.md
- src/Credentials.ts
- src/__tests__/Credentials-test.ts
- src/__tests__/__snapshots__/Credentials-test.ts.snap
Implements new [Claims Spec](https://github.com/uport-project/specs/pull/48)
Merge in #167 first
> Add support for claims spec

- README.md
- RELEASE-NOTES.md
- docs/guides/index.md
- docs/guides/tutorial.md
- docs/index.md
- docs/reference/index.md
- src/Credentials.ts
- whats-new.md
> docs: adjust sample code to changes in resolver requirements

- src/Credentials.ts
- src/__tests__/Credentials-test.ts
- src/__tests__/__snapshots__/Credentials-test.ts.snap
Add support for boxPub in Selective Disclosure Request, as described in https://developer.uport.me/messages/sharereq
> boxPub support for Selective Disclosure Request

- package-lock.json
- package.json
- src/Credentials.ts
- src/deps.d.ts
This commit also removes some unused constructor options
> chore(deps): remove unused dependencies

- src/Credentials.ts
> fix: make ClaimSpec.user_info and VerifiableClaimSpec.iss optional

- package-lock.json
- package.json
- src/Credentials.ts
- src/__tests__/Credentials-test.ts
Fixes failing https://github.com/uport-project/uport-credentials/pull/225 .
issueVerifiableCredential payload parameter type changed from `VerifiableCredentialPayload` to `JwtCredentialPayload | CredentialPayload`.
verifyPresentation return type changed from `PresentationPresponse` to `VerifiedPresentation`.
> Did jwt vc 1.x

- src/__tests__/Credentials-test.ts
trying to fix: https://github.com/uport-project/uport-credentials/pull/267
> fix(deps): getResolver needs an options parameter

- renovate.json
This should reduce dependency update noise
> chore(deps): reschedule renovate bot
